// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsYIKA1FGWhWl6VcWFDPqeF4mMOHLQMk8',
    appId: '1:907297647147:web:998bf16f206c479c81986e',
    messagingSenderId: '907297647147',
    projectId: 'marine-a6ffd',
    authDomain: 'marine-a6ffd.firebaseapp.com',
    storageBucket: 'marine-a6ffd.appspot.com',
    measurementId: 'G-4EBZCMR8C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt_-mfc5ma3yKdc9lhFBg9zXEbEUQnV5g',
    appId: '1:907297647147:android:6db375d11022914b81986e',
    messagingSenderId: '907297647147',
    projectId: 'marine-a6ffd',
    storageBucket: 'marine-a6ffd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm3EwCvXuuVpDX1GqyQDH6IslgtDS2XD4',
    appId: '1:907297647147:ios:26a117b7b9796d6881986e',
    messagingSenderId: '907297647147',
    projectId: 'marine-a6ffd',
    storageBucket: 'marine-a6ffd.appspot.com',
    iosClientId: '907297647147-vu33sg9eqsg4l9ndlvtehh4u0t7qk2gj.apps.googleusercontent.com',
    iosBundleId: 'com.example.marine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm3EwCvXuuVpDX1GqyQDH6IslgtDS2XD4',
    appId: '1:907297647147:ios:26a117b7b9796d6881986e',
    messagingSenderId: '907297647147',
    projectId: 'marine-a6ffd',
    storageBucket: 'marine-a6ffd.appspot.com',
    iosClientId: '907297647147-vu33sg9eqsg4l9ndlvtehh4u0t7qk2gj.apps.googleusercontent.com',
    iosBundleId: 'com.example.marine',
  );
}
